### ISSUE TITLE
Path should be represented in os independent form

### ISSUE THREAD

**Issue by johann-sonntagbauer** [christophwitzko/path-object#1]
Hi, I am having a hard time to use the git-ref module on windows because the paths in PathObject are not stored in os independent form. After parsing the refs from the .git/HEAD file the references look something like this `refs/heads/master` but the path.join produces `refs/heads/master` so the path can't be accessed. 

So my proposal would be to use something like https://github.com/sindresorhus/slash to convert the paths always into forward slashes. That solution should work for most cases. If you are pleased with that strategy i will try to formulate a pr. 

Thanks for the greate utils and keep up the good work!

**Comment by christophwitzko** [comment]
Hi,

thank you for help. I really appreciate it.
This is actually an issue with git-refs. I have already fixed it. (christophwitzko/git-refs@1c85d12)

have a great day
Christoph
